import assert from "node:assert/strict";
import test from "node:test";
import { mkdtemp, readFile, rm, mkdir, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { SmartCore } from "./core.ts";
import { createSmartServer } from "./http.ts";
import { createAcceptanceLibrary } from "../../../scripts/smart-cutter/fixture.ts";
import { registerCutterAccount, approveCutterUser, setCutterAccountTier, cutterAccountTier, ensureCutterSessionForDevice } from "../../library-fs/src/index.ts";
import { localClipToSourceVideoDetail } from "../../../apps/cutter-web/src/state/material-locator.ts";
import { selectionFromText } from "../../../apps/smart-cutter-web/src/basics.ts";
import type { SourceVideoDetail, CutJobSubmission, CutJobCatalog, LocalClipCatalog } from "../../../apps/cutter-web/src/api.ts";
import type { Assembly } from "./assembly.ts";
const ai = { python: "missing-test-runtime", script: "missing-test-runtime", models: "missing-test-runtime" };
async function until<T>(operation: () => Promise<T | null>): Promise<T> { const deadline = Date.now() + 60000; while (Date.now() < deadline) { const value = await operation(); if (value) return value; await new Promise(resolve => setTimeout(resolve, 80)); } throw new Error("real pipeline timed out"); }
test("shared approved accounts, old-account compatibility, real manual cut/recut/merge, Pro APIs and protected cleanup", { timeout: 150000 }, async t => {
  const root = await mkdtemp(path.join(os.tmpdir(), "mixlab-unified-"));
  const library = await createAcceptanceLibrary(path.join(root, "library"));
  const pointer = path.join(library, ".mixlab-library/current-release.json"), initialPointer = await readFile(pointer, "utf8");
  const core = new SmartCore({ state_root: path.join(root, "state"), workspace_root: path.join(root, "workspace"), auth_mode: "reviewed", ai }); await core.initialize();
  await core.updateSettings({ library_root: library });
  const registered = await registerCutterAccount(library, { username: "unified-test", password: "CutterTest12345", device_id: core.settings.device_id, device_name: "验收工作站", now: new Date().toISOString() });
  await approveCutterUser(library, { user_id: registered.user_id, now: new Date().toISOString() });
  const server = createSmartServer(core, "local-test-access"); await new Promise<void>(resolve => server.listen(0, "127.0.0.1", resolve));
  const base = `http://127.0.0.1:${(server.address() as {port: number}).port}`;
  t.after(async () => { await core.close(); await new Promise<void>(resolve => server.close(() => resolve())); core.store.close(); await rm(root, { recursive: true, force: true }); });
  async function api<T>(route: string, method = "GET", payload?: unknown, expected = 200): Promise<T> {
    const result = await fetch(base + route, { method, headers: { "X-Smart-Token": "local-test-access", "Content-Type": "application/json" }, ...(payload === undefined ? {} : {body: JSON.stringify(payload)}) });
    const value = await result.json(); assert.equal(result.status, expected, `${route}: ${JSON.stringify(value)}`); return route.startsWith("/cutter/") ? value.data : value;
  }
  await api("/cutter/source-library", "GET", undefined, 401);
  await api("/smart/auth/login", "POST", { username: "unified-test", password: "CutterTest12345" });
  assert.equal((await core.authStatus()).user?.tier, "ordinary");
  await api("/smart/works", "POST", { script: "现金流是企业的血液。" }, 403);
  await api("/smart/settings", "PUT", { tikhub_api_key: "forbidden" }, 403);
  const detail = await api<SourceVideoDetail>("/cutter/source-videos/V000001");
  const selected = selectionFromText(detail, { start: 0, end: 1, from: 2, to: 6 }, "precise")!;
  assert.equal(selected.selected_text, "流是企业的血液。把事情做对，"); assert.ok(selected.begin_ms > 0 && selected.end_ms > 2000);
  const project = await api<{id:string}>("/smart/projects", "POST", {title:"真实检索项目",items:[selected]}, 201);
  const list = await api<{clip_list_id:string}>("/cutter/clip-lists", "POST", {library_id:"smart-acceptance-only",project_id:project.id,title:"真实检索项目",items:[selected]}, 201);
  const submission = await api<CutJobSubmission>("/cutter/cut-jobs", "POST", {clip_list_id:list.clip_list_id}, 201);
  const job = await until(async () => { const catalog = await api<CutJobCatalog>("/cutter/cut-jobs"); const job = catalog.jobs.find(job=>job.cut_job_id===submission.jobs[0]!.cut_job_id)!; if (job.status === "failed") throw new Error(job.error_message); return job.status === "done" ? job : null; });
  assert.ok(job.export_clip_id);
  const locals = await api<LocalClipCatalog>("/cutter/local-clips"); assert.equal(locals.local_clip_count,1);
  const clip = locals.clips[0]!; const media = await fetch(base+clip.media_url,{headers:{"X-Smart-Token":"local-test-access"}}); assert.equal(media.status,200); assert.ok((await media.arrayBuffer()).byteLength>1000);
  const merge = await api<Assembly>("/smart/assemblies", "POST", {project_id:project.id,cut_job_ids:[job.cut_job_id,job.cut_job_id]},202);
  const completed = await until(async()=>{ await core.assemblies.drain(); const value = core.store.get<Assembly>("assembly",merge.id)!; if(value.status==="failed") throw new Error(value.error); return value.status==="done" ? value:null; });
  assert.equal(completed.completed,2); assert.ok(completed.duration_ms>4000);
  assert.ok((await readFile(path.join(path.dirname(completed.output_path),"sources.json"),"utf8")).includes(job.export_clip_id!));
  const localDetail = await api<LocalClipCatalog["clips"][number]>(`/cutter/local-clips/${clip.local_clip_id}`); assert.ok(localDetail.transcript_segments?.length);
  await api(`/smart/local/${clip.local_clip_id}`,"PATCH",{title:"改名后素材"});
  assert.equal((await api<LocalClipCatalog>("/cutter/local-clips")).clips[0]!.title,"改名后素材");
  const recut = selectionFromText(localClipToSourceVideoDetail(localDetail), {start:0,end:0,from:0,to:3}, "precise")!;
  const recutList = await api<{clip_list_id:string}>("/cutter/clip-lists", "POST", {library_id:"smart-acceptance-only",project_id:project.id,title:"复剪项目",items:[recut]},201);
  const recutSubmission = await api<CutJobSubmission>("/cutter/cut-jobs", "POST", {clip_list_id:recutList.clip_list_id},201);
  await until(async()=>{ const catalog=await api<CutJobCatalog>("/cutter/cut-jobs"); const result=catalog.jobs.find(job=>job.cut_job_id===recutSubmission.jobs[0]!.cut_job_id)!; if(result.status==="failed") throw new Error(result.error_message); return result.status==="done" ? result:null; });
  assert.equal((await api<LocalClipCatalog>("/cutter/local-clips")).local_clip_count,2);
  await setCutterAccountTier(library,registered.user_id,"pro");
  await ensureCutterSessionForDevice(library,{user_id:registered.user_id,device_id:core.settings.device_id,now:new Date().toISOString()});
  assert.equal(await cutterAccountTier(library,registered.user_id),"pro","legacy account mutations cannot discard Pro entitlement");
  const work=core.createWork("现金流是企业的血液。"); await core.generatePlan(work.id);
  const planned=core.work(work.id);
  await api(`/smart/works/${work.id}/segments/1/supplement`,"POST",{revision:planned.revision,source_video_id:"E000001",range:{start:0,end:0,from:0,to:10},begin_ms:0,end_ms:1700},400);
  const updated=await api<{revision:number}>(`/smart/works/${work.id}/segments/1/supplement`,"POST",{revision:planned.revision,source_video_id:"V000001",range:{start:0,end:0,from:0,to:10},begin_ms:0,end_ms:1700});
  assert.ok(updated.revision>planned.revision);
  await api(`/smart/works/${work.id}/segments/1/supplement`,"POST",{revision:planned.revision,source_video_id:"V000001",range:{start:0,end:0,from:0,to:10},begin_ms:0,end_ms:1700},409);
  await mkdir(path.join(core.settings.workspace_root,"cache/previews"),{recursive:true}); await writeFile(path.join(core.settings.workspace_root,"cache/previews/idle.mp4"),"fixture-cache");
  const output=await readFile(completed.output_path), localVideo=await readFile(path.join(core.manual.workspace,clip.relative_path!));
  await api("/smart/cache/clear","POST",{kinds:["temporary","index","source","reference"]});
  assert.deepEqual(await readFile(completed.output_path),output); assert.deepEqual(await readFile(path.join(core.manual.workspace,clip.relative_path!)),localVideo);
  assert.equal(await readFile(pointer,"utf8"),initialPointer);
  await setCutterAccountTier(library,registered.user_id,"ordinary"); await api(`/smart/works/${work.id}`,"GET",undefined,403); assert.equal((await core.state()).works.length,0);
  await api("/smart/auth/logout","POST",{}); await api("/cutter/local-clips","GET",undefined,401);
});
