import React, { useEffect, useState } from "react";
import { IconFolderOpen, IconSearch, IconRefresh, IconTrash, IconScissors, IconLock } from "@tabler/icons-react";
import { Button, Badge, Header, Empty, Modal, Banner } from "./components.tsx";
import { request, duration, dateText } from "./api.ts";
import type { Basics } from "./basics.ts";
import { cutterRequest } from "./basics.ts";
import type { WorkspaceCache, CacheKind } from "../../../packages/smart-cutter/src/cache.ts";
export function MaterialLibrary({ data, kind, onRetrieve }: { data: Basics; kind: "local" | "public"; onRetrieve: () => void }) {
  const [query, setQuery] = useState(""), [selectedId, setSelectedId] = useState(""), [dialog, setDialog] = useState(""), [name, setName] = useState("");
  const local = kind === "local";
  const cards = local ? data.locals.clips.map(clip => ({ id: clip.local_clip_id, title: clip.title, cover: clip.cover_url, text: clip.selected_text ?? "", duration: clip.duration_ms ?? 0, folder: "", width: clip.width ?? 0, height: clip.height ?? 0 })) : data.library.videos.map(video => ({ id: video.source_video_id, title: video.title, cover: video.cover_url, text: video.description ?? "", duration: video.duration_ms, folder: video.source_folder_name ?? "", width: video.width ?? 0, height: video.height ?? 0 }));
  const filtered = cards.filter(card => (!query || `${card.title}${card.text}`.includes(query)) && (data.orientation === "all" || (data.orientation === "portrait" ? card.height > card.width : card.width >= card.height)));
  const selected = cards.find(card => card.id === selectedId);
  const detail = data.detail?.source_video_id === selectedId ? data.detail : null;
  async function view(id: string) { await data.choose(id, kind); setSelectedId(id); setDialog("detail"); }
  return <><Header title={local ? "本地素材" : "公共素材库"} subtitle={local ? "查看本机保存的可复用片段，继续检索和剪切。" : "管理端发布的原视频、转写和索引，供本机检索使用。"}><Badge tone={local ? "blue" : ""}>{local ? "本机片段" : <><IconLock size={12} />公共库只读</>}</Badge><Button icon={IconRefresh} disabled={data.busy} onClick={() => void data.act(() => local ? data.refresh() : data.loadLibrary())}>刷新</Button></Header>
    <div className="material-scope"><strong>{local ? "可复用片段" : "已发布素材"}</strong><span>{local ? "独立剪切完成后自动登记；完整视频在本地成果中查看。" : "监控参考视频仅用于提取文案，不进入这里。"}</span></div>
    <div className="filterbar"><input aria-label={local ? "筛选本地素材" : "筛选公共素材"} placeholder="按名称或已加载文案筛选" value={query} onChange={event => setQuery(event.target.value)} />{!local && <select aria-label="公共素材文件夹" value={data.folder} onChange={event => data.setFolder(event.target.value)}><option value="">全部文件夹</option>{data.folders.map(folder => <option key={folder.name}>{folder.name}</option>)}</select>}<select aria-label="素材方向" value={data.orientation} onChange={event => data.setOrientation(event.target.value)}><option value="all">全部方向</option><option value="portrait">竖屏</option><option value="landscape">横屏</option></select><span className="small muted grow" style={{ textAlign: "right" }}>已加载 {cards.length} / {local ? data.locals.local_clip_count : data.library.available_video_count}</span></div>
    {data.failure && <Banner tone="amber">{data.failure}</Banner>}
    <div className="material-grid">{filtered.map(card => <div className="material-card panel" key={card.id}><button className="material-cover" aria-label={`查看${card.title}`} onClick={() => void data.act(() => view(card.id))}>{card.cover ? <img src={card.cover} alt={card.title} /> : <IconFolderOpen size={26} />}<Badge>{duration(card.duration)}</Badge></button><div className="material-info"><h3>{card.title}</h3><p>{card.folder || (local ? "本地可复剪素材" : "已发布 · 转写就绪")}</p><div className="material-copy">{card.text || "进入文案检索查看完整转写"}</div><div className="row between material-actions"><Button small onClick={() => void data.act(() => view(card.id))}>查看详情</Button><button className="text-btn" onClick={() => void data.act(async () => { await data.choose(card.id, kind); data.setScope(kind); onRetrieve(); })}>{local ? "继续拖选" : "检索文案"}<IconScissors size={13} /></button></div></div></div>)}</div>{!filtered.length && <Empty>{cards.length ? "没有符合筛选的素材" : local ? "还没有本地素材，剪切完成后会出现在这里" : "还没有可用的已发布素材，请检查公共库路径"}</Empty>}
    {local && data.locals.clips.length < data.locals.local_clip_count && <Button style={{marginTop:16}} disabled={data.busy} onClick={() => void data.act(() => data.loadMore("local"))}>继续加载200条本地素材</Button>}
    {!local && data.library.videos.length < data.library.available_video_count && <Button style={{ marginTop: 16 }} disabled={data.busy} onClick={() => void data.act(() => data.loadLibrary(true))}>继续加载20条</Button>}
    {dialog === "detail" && selected && <Modal title={selected.title} wide onClose={() => setDialog("")} footer={<><Button onClick={() => setDialog("")}>关闭</Button>{local && <><Button icon={IconFolderOpen} onClick={() => void data.act(() => cutterRequest("/cutter/workspace/open-export-directory", "POST", {}))}>打开本地目录</Button><Button onClick={() => { setName(selected.title); setDialog("rename"); }}>重命名</Button><Button variant="danger" icon={IconTrash} onClick={() => setDialog("delete")}>删除素材</Button></>}<Button variant="primary" icon={IconSearch} onClick={() => { data.setScope(kind); setDialog(""); onRetrieve(); }}>{local ? "继续拖选" : "进入文案检索"}</Button></>}><div className="real-media">{detail && <video controls preload="metadata" src={detail.media_url} poster={detail.cover_url} />}</div><div className="detail-pairs"><div><label>来源</label><p>{local ? data.locals.clips.find(clip => clip.local_clip_id === selectedId)?.source_title : "管理端发布"}</p></div><div><label>素材时长</label><p>{duration(selected.duration)}</p></div><div><label>分辨率</label><p>{selected.width} × {selected.height}</p></div><div><label>视频文件</label><p>{detail?.relative_path || selectedId}</p></div></div><div className="script-block">{detail?.transcript.full_text || selected.text}</div></Modal>}
    {dialog === "rename" && selected && <Modal title="重命名本地素材" onClose={() => setDialog("")} footer={<><Button onClick={() => setDialog("")}>取消</Button><Button variant="primary" disabled={!name.trim() || data.busy} onClick={() => void data.act(async () => { await request(`/smart/local/${selected.id}`, "PATCH", { title: name }); await data.refresh(); setDialog(""); })}>保存名称</Button></>}><label>素材名称<input aria-label="素材名称" value={name} onChange={event => setName(event.target.value)} style={{ width: "100%" }} /></label><p className="module-note">修改素材列表名称，保留来源信息与剪切时间。</p></Modal>}
    {dialog === "delete" && selected && <Modal title="删除本地素材" onClose={() => setDialog("")} footer={<><Button onClick={() => setDialog("")}>取消</Button><Button variant="danger" disabled={data.busy} onClick={() => void data.act(async () => { await request(`/smart/local/${selected.id}`, "DELETE"); await data.refresh(); setDialog(""); })}>确认删除本机文件</Button></>}><p>将删除「{selected.title}」及对应的本机视频和转写。公共源视频不受影响。已保存清单中的引用将无法继续复剪。</p></Modal>}
  </>;
}
const CACHE_NAMES: Record<CacheKind, string> = { source: "素材视频缓存", temporary: "预览与剪切临时文件", index: "已发布索引与语义索引", reference: "监控参考视频与音频" };
const bytes = (value: number): string => value >= 1024 ** 3 ? `${(value / 1024 ** 3).toFixed(2)} GB` : value >= 1024 ** 2 ? `${(value / 1024 ** 2).toFixed(1)} MB` : `${(value / 1024).toFixed(1)} KB`;
type CacheStatus = Awaited<ReturnType<WorkspaceCache["status"]>>;
export function CacheManagement({ sourceLimit, onLimit }: { sourceLimit: number; onLimit: (value: number) => Promise<void> }) {
  const [status, setStatus] = useState<CacheStatus | null>(null), [selected, setSelected] = useState<CacheKind[]>(["source", "temporary", "reference"]);
  const [confirm, setConfirm] = useState(false), [busy, setBusy] = useState(false), [limit, setLimit] = useState(String(sourceLimit)), [error, setError] = useState("");
  async function refresh() { try { setStatus(await request<CacheStatus>("/smart/cache")); setError(""); } catch (failure) { setError((failure as Error).message); } }
  useEffect(() => { void refresh(); }, []);
  const entries = status?.entries ?? [], total = entries.reduce((sum, item) => sum + item.used_bytes, 0), clearable = entries.reduce((sum, item) => sum + item.clearable_bytes, 0), protectedBytes = total - clearable;
  const selectedBytes = entries.filter(item => selected.includes(item.kind)).reduce((sum, item) => sum + item.clearable_bytes, 0);
  return <><Header title="缓存管理" subtitle="查看和清理本机可再生成的缓存，保存的素材、项目和成片保留。"><Button icon={IconRefresh} disabled={busy} onClick={() => void refresh()}>刷新占用</Button></Header>{error && <Banner tone="amber">{error}</Banner>}<div className="cache-stats"><div className="panel"><span>当前缓存占用</span><strong>{bytes(total)}</strong></div><div className="panel"><span>当前可清理</span><strong>{bytes(clearable)}</strong></div><div className="panel"><span>受保护缓存</span><strong>{bytes(protectedBytes)}</strong></div></div><section className="panel"><div className="panel-head"><h2>按用途选择清理范围</h2><Badge tone="blue">活动任务与检查点受保护</Badge></div><div className="table-wrap"><table className="table"><thead><tr><th>清理</th><th>缓存类别</th><th>占用</th><th>可清理</th><th>受保护</th></tr></thead><tbody>{entries.map(item => <tr key={item.kind}><td><input type="checkbox" aria-label={`清理${CACHE_NAMES[item.kind]}`} checked={selected.includes(item.kind)} disabled={!item.clearable_bytes} onChange={event => setSelected(values => event.target.checked ? [...values, item.kind] : values.filter(value => value !== item.kind))} /></td><td>{CACHE_NAMES[item.kind]}{item.kind === "index" && <p className="small muted">已锁定的发布快照保留，保证已有作品可以继续处理。</p>}</td><td>{bytes(item.used_bytes)}</td><td>{bytes(item.clearable_bytes)}</td><td>{bytes(item.protected_bytes)}</td></tr>)}</tbody></table></div><div className="panel-foot row between"><span className="small muted">已选择 {bytes(selectedBytes)} · 上次清理 {status?.last_cleanup ? dateText(status.last_cleanup) : "尚未清理"}</span><Button variant="primary" disabled={busy || !selectedBytes} icon={IconTrash} onClick={() => setConfirm(true)}>预览清理范围</Button></div></section><div className="panel panel-pad" style={{ marginTop: 18 }}><div className="settings-row"><div><h3>素材视频缓存上限（GB）</h3><p>接近上限时优先淘汰闲置素材，正在使用的缓存保留。</p></div><input type="number" aria-label="素材缓存上限" min="1" max="500" value={limit} onChange={event => setLimit(event.target.value)} /><Button disabled={busy || !Number.isFinite(Number(limit)) || Number(limit) < 1 || Number(limit) > 500} onClick={() => { setBusy(true); void onLimit(Number(limit)).catch(failure => setError((failure as Error).message)).finally(() => setBusy(false)); }}>保存上限</Button></div></div>{confirm && <Modal title="确认缓存清理范围" onClose={() => setConfirm(false)} footer={<><Button onClick={() => setConfirm(false)}>取消</Button><Button variant="primary" disabled={busy} onClick={() => { setBusy(true); void request<CacheStatus>("/smart/cache/clear", "POST", { kinds: selected }).then(value => { setStatus(value); setConfirm(false); }).catch(failure => setError((failure as Error).message)).finally(() => setBusy(false)); }}>清理闲置缓存</Button></>}><p>预计释放 {bytes(selectedBytes)}。执行时会重新检查活动任务和正在播放的视频；受保护缓存、本地素材、项目和成果保留。</p><div className="module-note">{selected.map(kind => CACHE_NAMES[kind]).join("、")}</div></Modal>}</>;
}
