import React, { useState } from "react";
import { IconFolderOpen, IconCheck, IconRefresh, IconLogout } from "@tabler/icons-react";
import { Button, Badge, Banner, Header } from "./components.tsx";
import { request, type AppState } from "./api.ts";
type Prefs = AppState["settings"];
interface Props {
  state: AppState; prefs: Prefs; setPrefs: React.Dispatch<React.SetStateAction<Prefs | null>>;
  pro: boolean; busy: boolean; authenticated: boolean;
  tikhubKey: string; setTikhubKey: (value: string) => void; asrKey: string; setAsrKey: (value: string) => void;
  save: () => Promise<void>; choose: (field: "library_root" | "workspace_root") => Promise<void>;
  act: <T>(operation: () => Promise<T>, message?: string) => Promise<T | null>; login: React.ReactNode; onCache: () => void;
}
export function UnifiedSettings(p: Props) {
  const [oldPassword, setOldPassword] = useState(""), [newPassword, setNewPassword] = useState("");
  const field = <K extends keyof Prefs>(key: K, value: Prefs[K]) => p.setPrefs(current => current ? { ...current, [key]: value } : current);
  const runtime = p.state.settings.runtime;
  return <><Header title="设置" subtitle="公共素材、账号与本机运行配置。"><Button variant="primary" icon={IconCheck} disabled={p.busy} onClick={() => void p.save()}>保存配置</Button></Header>
    <div className="settings-sections"><section className="panel"><div className="panel-head"><h2>素材与本机目录</h2><Badge>本机执行</Badge></div><div className="panel-pad">
      {([ ["library_root", "公共素材库", "读取管理端已发布的素材、转写和索引。"], ["workspace_root", "本机工作区", "使用独立的本机目录保存项目、剪切片段与成片。"] ] as const).map(([key, label, help]) => <div className="form-group" key={key}><label htmlFor={`settings-${key}`}>{label}</label><div className="row"><input id={`settings-${key}`} className="grow" value={p.prefs[key]} onChange={event => field(key, event.target.value)} /><Button icon={IconFolderOpen} onClick={() => void p.choose(key)}>选择目录</Button></div><p className="module-note">{help}</p></div>)}
      {p.authenticated && <div className="row"><Button disabled={p.busy} icon={IconRefresh} onClick={() => void p.act(() => request("/smart/library/sync", "POST", {}), "已开始同步发布素材")}>同步发布素材</Button><Button onClick={p.onCache}>管理缓存</Button></div>}
    </div></section>
    <section className="panel"><div className="panel-head"><h2>账号与权限</h2>{p.authenticated && <Badge tone={p.pro ? "blue" : ""}>{p.pro ? "Pro 账号" : "普通账号"}</Badge>}</div><div className="panel-pad">{p.authenticated ? <><p>当前账号：{p.state.auth.user?.username}</p><p className="module-note">使用管理端审核的剪辑师账号。Pro 权限由管理端配置。</p><details className="optional-settings"><summary>修改密码</summary><div className="form-group"><label htmlFor="old-password">原密码</label><input id="old-password" type="password" autoComplete="current-password" value={oldPassword} onChange={event => setOldPassword(event.target.value)} /></div><div className="form-group"><label htmlFor="new-password">新密码</label><input id="new-password" type="password" autoComplete="new-password" value={newPassword} onChange={event => setNewPassword(event.target.value)} /></div><Button disabled={p.busy || !oldPassword || !newPassword} onClick={() => void p.act(async () => { await request("/smart/auth/password", "POST", { current_password: oldPassword, new_password: newPassword }); setOldPassword(""); setNewPassword(""); }, "密码已修改，请重新登录")}>修改密码</Button></details><Button icon={IconLogout} disabled={p.busy} onClick={() => void p.act(() => request("/smart/auth/logout", "POST", {}), "已退出登录")}>退出登录</Button></> : p.login}</div></section>
    {p.pro && <><section className="panel"><div className="panel-head"><h2>监控平台与接口</h2><Badge tone="blue">Pro</Badge></div><div className="panel-pad"><div className="form-group"><label htmlFor="monitor-platform">监控平台</label><select id="monitor-platform" value={p.prefs.monitor_platform} onChange={event => field("monitor_platform", event.target.value as "douyin")}><option value="douyin">抖音 · TikHub</option></select></div><div className="form-group"><label htmlFor="tikhub-key">TikHub API Key</label><input id="tikhub-key" type="password" autoComplete="off" value={p.tikhubKey} onChange={event => p.setTikhubKey(event.target.value)} placeholder={p.state.settings.has_tikhub_key ? "已保存，填写以替换" : "填写 API Key"} /></div><div className="row"><Button disabled={p.busy || !p.state.settings.has_tikhub_key} onClick={() => void p.act(() => request("/smart/provider/test", "POST", {}), "TikHub 连接正常")}>测试连接</Button><Button disabled={p.busy || !p.state.settings.has_tikhub_key} variant="danger" onClick={() => void p.act(() => request("/smart/settings", "PUT", { clear_tikhub_key: true }), "TikHub 密钥已清除")}>清除密钥</Button></div><div className="detail-pairs">{([ ["monitor_interval_minutes", "监控间隔（分钟）", 5, 1440], ["request_limit_per_day", "每日请求上限", 1, 10000], ["reference_cache_gb", "参考缓存上限（GB）", 1, 500], ["max_download_mb", "单视频上限（MB）", 10, 10000] ] as const).map(([key, label, min, max]) => <label key={key}>{label}<input type="number" min={min} max={max} value={p.prefs[key]} onChange={event => field(key, Number(event.target.value))} /></label>)}</div><p className="module-note">下载视频只用于提取参考文案，不加入剪辑素材库。密钥保存在本机，不回显。</p></div></section>
    <section className="panel"><div className="panel-head"><h2>文案提取与智能匹配</h2><Badge tone="blue">Pro</Badge></div><div className="panel-pad"><div className="form-group"><label htmlFor="asr-key">语音转写 API Key（DashScope）</label><input id="asr-key" type="password" autoComplete="off" value={p.asrKey} onChange={event => p.setAsrKey(event.target.value)} placeholder={p.state.settings.has_asr_key ? "已保存，填写以替换" : "填写 API Key"} /></div><div className="form-group"><label htmlFor="asr-model">转写模型</label><input id="asr-model" value={p.prefs.asr_model} onChange={event => field("asr_model", event.target.value)} /></div><div className="row"><Button disabled={p.busy || !p.state.settings.has_asr_key} variant="danger" onClick={() => void p.act(() => request("/smart/settings", "PUT", { clear_asr_key: true }), "转写密钥已清除")}>清除转写密钥</Button><Button disabled={p.busy || runtime.semantic.running} onClick={() => void p.act(() => request("/smart/library/index", "POST", {}), "已开始建立语义索引")}>建立语义索引</Button>{runtime.semantic.running && <Button onClick={() => void p.act(() => request("/smart/library/index/stop", "POST", {}))}>停止建索引</Button>}</div><p className="module-note">原文检索使用已有发布索引；语义匹配需要本机模型与语义索引就绪。</p></div></section></>}
    <section className="panel"><div className="panel-head"><h2>运行状态</h2></div><div className="panel-pad">{[["媒体引擎", runtime.ffmpeg_ready ? "已就绪" : "未就绪"], ["公共素材", runtime.library_ready ? `${runtime.library_count} 条 · ${runtime.library_version}` : runtime.library_error || "待同步"], ...(p.pro ? [["智能模型", runtime.ai_ready ? "已就绪" : "未就绪"]] : []), ["密钥保护", p.state.settings.credential_protection]].map(([label, value]) => <div className="scope-line" key={label}><span>{label}</span><strong>{value}</strong></div>)}<div className="space" /><Banner>桌面端关闭窗口后留在托盘继续处理。通过托盘“退出应用”才停止本机引擎。</Banner></div></section></div></>;
}
