import { createHash } from "node:crypto";
import { chmod, copyFile, mkdir, readdir, readFile, rm, stat, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import {
  createNasAcceptanceEvidenceDraft,
  createNasConcurrencyReportDraft,
  createWindowsAcceptanceEvidenceDraft,
  type TargetEvidenceDraftOptions
} from "./target-evidence-template.ts";
import { TARGET_EVIDENCE_KIT_ARTIFACT_NAME } from "./target-evidence.ts";

export const EVIDENCE_KIT_DIR = path.join("dist", "acceptance", "mixlab-evidence-kit");
const DEFAULT_NAS_PREPROCESS_COUNT_REFRESH_INTERVAL = 25;
export const OPTIONAL_LOCAL_SOURCE_REPORTS = [
  {
    source_path: path.join("docs", "acceptance", "local-web-real-nas.md"),
    kit_path: "local/local-web-real-nas.md"
  },
  {
    source_path: path.join("docs", "acceptance", "artifacts", "local-web-sanity.json"),
    kit_path: "local/local-web-sanity.json"
  },
  {
    source_path: path.join("docs", "acceptance", "artifacts", "real-nas-50-editor-report.json"),
    kit_path: "local/real-nas-50-editor-report.json"
  }
] as const;

const LOCAL_SOURCE_REPORTS_README = `# Local Source-Machine Evidence

This folder is included only when source-machine reports or the local Web acceptance record already exist in the repository workspace during \`npm run package:evidence-kit\`.

These artifacts document the current local Web phase against the real NAS-mounted library. Start with \`local-web-real-nas.md\` when it is present, then compare the saved JSON reports. They are useful for handoff and comparison, but they do not replace ACC-008 Windows target evidence, ACC-009 NAS Docker/SMB target evidence, or the final combined target gate.

Files in this folder:

- \`local-web-real-nas.md\`: human acceptance record for the local Web admin and cutter against the real NAS-mounted public library.
- \`local-web-sanity.json\`: structured source-machine audit proving admin dashboard/searchd parity, admin route rendering, source-videos Web UI proof for the real NAS library, source-videos write-lock proof, real NAS preprocessing visibility, visible preprocessing safety labels, Material Locator search, full-transcript hit location, sentence-context selection, local clip creation, Cut Tasks visibility, and public-library write protection.
- \`real-nas-50-editor-report.json\`: source-machine 50-editor rehearsal report for searchd/full-transcript-location/selection/local-clip behavior at final target scale.

Before using this folder as handoff evidence, run \`npm run status:local-real-nas\` in the source repository for a no-side-effect live check of the running admin web, cutter web, APIs, searchd, and saved snapshot drift. If it reports \`ready_for_manual_web_test = true\`, local Web exploratory testing can proceed against the real NAS data. If it reports hot-refresh warnings with \`ready_for_evidence_refresh = false\`, wait until Admin/Searchd/Cutter index signals settle before refreshing evidence. Then rerun \`npm run sync:local-real-nas-record\`, then \`npm run audit:local-real-nas-phase\` in the source repository. The sync step refreshes \`local-web-real-nas.md\` from the saved local Web JSON so hot-refreshed NAS index versions, hit counts, local clip ids, and cut job ids cannot drift from the structured report. The audit step's \`local_web\` summary must include \`source_video_web_first_id\`, \`source_video_web_loaded_after\`, \`source_video_web_query_response_observed\`, \`source_video_web_ready_filter_all_visible_rows_ready\`; \`dashboard_write_action_lock_labels\` with \`智能扫描\`; \`source_video_write_action_lock_labels\` with \`重试此视频\`, \`保存封面\`, and \`保存公开说明\`; \`preprocess_safety_labels\` with \`真实 NAS 安全边界\`, \`只读观察\`, \`人工确认\`, and \`本机工作区\`; \`preprocess_write_action_lock_labels\` with \`重试失败\`, \`发布待索引视频\`, \`校验索引\`, \`恢复处理中任务\`, \`启动预处理流水线\`, and \`暂停预处理流水线\`; \`material_query\`; \`material_candidate_count\`; \`selection_proof_text\`; \`selected_text_char_count\`; \`selected_text_is_broader_than_query=true\`; \`local_clip_id\`; \`cut_job_id\`; and \`public_library_write_detected=false\`.

These local reports prove the current source-machine Web preflight only. They do not prove a clean Windows 10/11 cutter desktop target, a NAS Docker/SMB admin target, target-machine artifact provenance, or the final ACC-008/ACC-009 combined gate.
`;

const ROOT_README = `# MixLab Target Evidence Kit

This folder is generated by \`npm run package:evidence-kit\`.

It is safe to copy the \`windows\` folder to clean Windows 10/11 target machines and the \`nas\` folder to the NAS shell host. The target machines do not need the MixLab source repository.

Open \`TESTER-CHECKLIST.md\` before the target run. It keeps local web sanity checks, Windows ACC-008 collection, NAS ACC-009 collection, and final repository validation in one operator-facing sequence. From the source repository, \`npm run status:local-real-nas\` performs a read-only live check before manual testing or evidence refresh; \`ready_for_manual_web_test = true\` means the local Web admin/cutter can be tested against real NAS data, while \`ready_for_evidence_refresh = false\` with warnings means Admin/Searchd/Cutter hot-refresh drift is still blocking formal evidence refresh. Warnings also identify saved snapshot drift without producing a local clip. \`npm run audit:local-web-sanity\` checks the running admin web, admin API, cutter web, cutter API, and searchd endpoints, verifies the admin dashboard core-path and 50-editor capacity signals, records admin_dashboard.active_cutter_count plus admin_dashboard.cutter_capacity with capacity at least 50, records admin_dashboard.current_index_version, records searchd_index.index_version and requires it to match the admin current index after the searchd hot-refresh window, records \`admin_dashboard.disabled_write_action_labels\` for \`智能扫描\`, records admin_real_nas_matrix to prove real PublicLibrary status, source folder settings, ready source detail transcript counts, preprocess jobs, index versions, cutter users, admin Web route rendering, admin_real_nas_matrix.source_video_web source-videos UI proof for real path visibility, first source id, load-more growth, query API response, and ready-filter rows, disabled source-videos write action labels for \`重试此视频\`, \`保存封面\`, and \`保存公开说明\`, visible preprocessing safety labels for \`真实 NAS 安全边界\`, \`真实 NAS 写入动作\`, \`未解锁\`, \`只读观察\`, \`人工确认\`, and \`本机工作区\`, disabled preprocessing write action labels for \`重试失败\`, \`发布待索引视频\`, \`校验索引\`, \`恢复处理中任务\`, \`启动预处理流水线\`, and \`暂停预处理流水线\`, and skipped mutating actions, records cutter_search_matrix to prove multiple keyword searches all use searchd and match searchd health, records layout.admin_statusbar, layout.admin_statusbar_item_overflow_count, layout.cutter_workbench, layout.cutter_body, layout.admin_route_layouts, and layout.cutter_route_layouts to reject horizontal overflow in the local Web admin and cutter workbench across the main route matrix at desktop 1440x960 and compact 1024x768 viewports, records material_locator.search_index_version and requires the actual Material Locator search result index to match searchd health, records admin_dashboard.search_p95_ms as a structured millisecond SLA field no higher than 1000ms, records admin_dashboard.local_search_coverage_percent as a structured percentage field at least 80%, records admin_dashboard.search_failure_count as 0, records material_locator.current_hit_time_ms_value, material_locator.global_hit_position, material_locator.global_hit_count, material_locator.current_video_hit_count, material_locator.selected_sentence_count, and material_locator.full_transcript_char_count as structured hit-to-transcript fields, requires current-video hit count not to exceed the global hit count, requires full transcript character count to exceed the selected transcript text length, requires selected transcript text to include broader sentence context than the query keyword alone through material_locator_closed_loop.selection_proof_text, material_locator_closed_loop.selected_text_char_count, and material_locator_closed_loop.selected_text_is_broader_than_query, and verifies the cutter Material Locator local cut feedback plus material_locator_closed_loop local_clip_id, local media/manifest paths, local media/manifest existence and positive byte sizes, cut_job_id, cut_job_status=done, cut_job_export_clip_id mapped to local_clip_id, cut job output, Cut Tasks page selected-text/output/completed-status visibility, local_output_is_outside_public_library, and public_library_write_detected=false before manual capture. Set \`MIXLAB_LOCAL_WEB_SANITY_REPORT=docs/acceptance/artifacts/local-web-sanity.json\` to keep the JSON report as a local audit artifact, then run \`npm run validate:local-web-sanity-report -- docs/acceptance/artifacts/local-web-sanity.json\` to revalidate the saved report. After the source-machine 50-editor report exists, run \`npm run sync:local-real-nas-record\` to refresh \`docs/acceptance/local-web-real-nas.md\` from the saved JSON, then run \`npm run audit:local-real-nas-phase\` to confirm the local Web report, the 50-editor report, and \`docs/acceptance/local-web-real-nas.md\` still agree; its summary must include local_web.source_video_web_first_id, local_web.source_video_web_loaded_after, local_web.source_video_web_query_response_observed, local_web.source_video_web_ready_filter_all_visible_rows_ready, local_web.dashboard_write_action_lock_labels, local_web.source_video_write_action_lock_labels, local_web.preprocess_safety_labels, local_web.preprocess_write_action_lock_labels, material_query, material_candidate_count, selection_proof_text, selected_text_char_count, selected_text_is_broader_than_query, local_clip_id, cut_job_id, and public_library_write_detected=false. The local Web sanity report is a source-machine preflight only; it does not replace ACC-008 Windows target evidence, ACC-009 NAS target evidence, or the final combined target gate. Override \`MIXLAB_ADMIN_WEB_URL\` or \`MIXLAB_ADMIN_WEB_BASE_URL\`, \`MIXLAB_ADMIN_API_BASE_URL\`, \`MIXLAB_CUTTER_WEB_URL\` or \`MIXLAB_CUTTER_WEB_BASE_URL\`, \`MIXLAB_CUTTER_API_BASE_URL\`, \`MIXLAB_SEARCHD_BASE_URL\`, \`MIXLAB_LOCAL_WEB_SANITY_QUERY\`, or \`MIXLAB_LOCAL_WEB_SANITY_MATRIX_QUERIES\` for non-default endpoints.

The local Web closed loop must prove manual full-transcript drag selection, not only a current-hit shortcut: \`material_locator_closed_loop.selection_method\` must equal \`transcript-drag\`, \`material_locator_closed_loop.selected_sentence_count\` must be at least 2, and \`material_locator_closed_loop.selected_text_segment_count\` must be at least 2 before cutting.

After each target-side collector run, use the local self-check before copying evidence back to the repository. These scripts are read-only and do not replace the repository validators; they only catch draft markers and missing referenced attachments while the target machine is still in front of the tester:

\`\`\`powershell
powershell -ExecutionPolicy Bypass -File .\\windows-evidence-self-check.ps1 -EvidencePath .\\windows-acc-008.json
\`\`\`

\`\`\`sh
sh ./nas-evidence-self-check.sh ./nas-acc-009.json
\`\`\`

Before the NAS collector copies a completed raw 50-editor rehearsal report into the evidence package, check that report directly:

\`\`\`sh
sh ./nas-50-editor-report-self-check.sh ./captures/50-editor-report.json
\`\`\`

After target collection, copy the completed evidence package back to the repository with attachment folders intact: \`windows-acc-008.json\` plus \`screenshots/\`, and \`nas-acc-009.json\` plus \`evidence/\`, under \`docs/acceptance/evidence/\`. Keep the relative paths written by the collectors before validating. Keep \`MANIFEST.json\` with the downloaded kit so the tester can confirm the copied target folders still contain the expected collectors, self-checks, README files, and draft JSONs:

\`\`\`sh
npm run audit:target-evidence-readiness
npm run validate:windows-evidence -- docs/acceptance/evidence/windows-acc-008.json
npm run validate:nas-evidence -- docs/acceptance/evidence/nas-acc-009.json
npm run validate:target-evidence -- docs/acceptance/evidence/windows-acc-008.json docs/acceptance/evidence/nas-acc-009.json
\`\`\`

\`npm run audit:target-evidence-readiness\` is the short repository-side status report for returned target evidence. It intentionally exits nonzero until ACC-008 and ACC-009 are both present, readable, validated, and tied to the same repository commit; use its \`next_actions\` output to decide whether to return to Windows collection, NAS collection, or final validation.

Every completed evidence JSON must include artifact_provenance.repository_commit_sha as a 40-character commit SHA, evidence_kit_artifact_name: "mixlab-target-evidence-kit", and the official https://github.com/alin155/mixlab GitHub Actions run URL that produced the evidence kit. When this kit is generated inside GitHub Actions, those provenance fields are prefilled from GITHUB_SHA and the current run URL. Windows evidence must also record the installer workflow run URL, version, file name, and SHA-256 digest. NAS evidence must use the same commit SHA as deployment.image_tag, record deployment.preprocess_count_refresh_interval as a positive integer from the NAS worker configuration, and include admin_source_videos_ui proof that the deployed NAS admin source-videos page shows the real source path, renders a concrete source video id, increases loaded rows through load-more, observes the query API response, and renders ready-filter rows only. The NAS collector preserves the prefilled provenance, image tag, deployment.preprocess_count_refresh_interval, and existing admin_source_videos_ui values from an existing nas-acc-009.json when matching environment variables are not supplied on the NAS shell host. The final combined gate rejects evidence when ACC-008 and ACC-009 do not reference the same repository commit.

The individual evidence validators reject non-portable or mismatched attachment references before final packaging: use forward-slash relative attachment paths only; absolute paths, URLs, backslash separators, and parent-directory traversal are rejected. Attachment filenames must match their evidence fields, such as doctor-pass, engine-status, material-locator, cut-job, local-library, admin-web, current-json, smb-permissions, worker, and 50-editor-report. The same individual validators also check that every referenced screenshot, log, and report file exists beside the evidence JSON, and the final combined gate reuses those checks. Screenshot attachments must be real .png, .jpg, .jpeg, or .webp files with matching file signatures and readable dimensions of at least 640x360; .json attachments must parse as JSON. The NAS worker_log_excerpt must include count_refresh_interval matching deployment.preprocess_count_refresh_interval. The NAS multi_user_search_cut_report JSON must prove status: "passed", top-level pass flags for search, local-workspace cuts, public-library write protection, and cross-workspace isolation, at least 50 editors, at least 50 distinct source_video_id values, at least 5 distinct search_query values with search_query_count and search_queries matching the per-editor queries, at least 2,000 indexed source videos, at least 48,000 indexed transcript segments, searchd_health_index_version equal to top-level search_index_version, searchd_health_source_video_count equal to indexed_source_video_count, searchd_health_segment_count equal to indexed_transcript_segment_count, positive search_sla_ms, detail_sla_ms, and cut_sla_ms values no higher than 1500, complete search/detail/cut latency summaries with min_ms <= p50_ms <= p95_ms <= max_ms, each search/detail/cut p95_ms no higher than its matching SLA field, editor_count and active_user_count equal to editor_sessions.length, distinct_source_video_count equal to the unique source_video_id values in editor_sessions, each latency count equal to editor_sessions.length, each latency max_ms at least the maximum matching per-editor timing, usage counts for search, full transcript views, selections, cut submissions, successful cuts, and local clips each at least editor_sessions.length, metrics.usage.search_failure_count equal to 0, plus editor_sessions with at least 50 unique user_id values, at least 50 unique workspace_id values, top-level search_index_version matching every per-editor search_index_version from searchd, and per-editor search hit to full transcript location, search_result_rank inside the returned result list, search_result_group_count at least search_result_limit, search_result_limit at least 50, integer search_result_begin_char/search_result_end_char values mapped into the full-transcript character offsets, search_result_text_sha256 equal to sha256(search_query), full_transcript_source_video_id matching source_video_id, full_transcript_segment_count at least 4, full_transcript_char_count greater than selected_text_char_count, full_transcript_text_sha256, integer selected_text_begin_char/selected_text_end_char values inside the full transcript that include the search hit range, selected_text_char_count equal to selected range length, local_clip_source_video_id matching source_video_id, local_clip_selected_text_sha256 equal to selected_text_sha256, local_clip_relative_path as a workspace-relative portable path, local_clip_file_size_bytes as positive output file size, local_clip_content_sha256 as output file sha256, local_clip_begin_ms/local_clip_end_ms matching selected_begin_ms/selected_end_ms, selection, local-clip, and workspace-output proof. It must not include target-machine run root fields such as library_root, workspace_root, or searchd_cache_root. Text attachments such as logs, JSON reports, CSV/TSV files, subtitles, and Markdown notes are scanned for forbidden secret or private-transcript markers.

When running the repository-based NAS rehearsal, use npm run smoke:searchd-nas-rehearsal to generate captures/50-editor-report.json at the same 2,000-video / 48,000-segment minimum scale required by the final gate. For real NAS preprocessing runs, keep MIXLAB_PREPROCESS_COUNT_REFRESH_INTERVAL=25 unless the NAS UI needs more frequent count updates; successful items refresh aggregate library counts at that interval and once at worker-cycle end, while failures still refresh immediately.

Windows screenshot attachments must be OS-specific. Keep Windows 10 screenshots under screenshots/windows-10/ and Windows 11 screenshots under screenshots/windows-11/; the final gate rejects reused screenshot paths across environments.

Do not paste ASR keys, signed URLs, full private transcripts, pasted search text, or non-redacted bearer tokens into evidence JSON files or text attachments. Target collectors reject empty attachments, reject these text markers before copying text diagnostics, logs, JSON reports, and other text attachments, and reject screenshot attachments whose .png, .jpg, .jpeg, or .webp extension does not match the file signature. The final combined gate also rejects screenshots smaller than 640x360. On NAS hosts with Node or Python 3 available, .json attachments are parsed before copying.

The Target Evidence Kit GitHub Actions workflow requires committed local source-machine evidence to be all-or-none: \`docs/acceptance/local-web-real-nas.md\`, \`docs/acceptance/artifacts/local-web-sanity.json\`, and \`docs/acceptance/artifacts/real-nas-50-editor-report.json\` must be committed together, or none of them should be committed. When all three are present, CI runs \`npm run validate:local-web-sanity-report -- docs/acceptance/artifacts/local-web-sanity.json\`, runs \`npm run sync:local-real-nas-record\` plus a clean git diff check, and runs the local real NAS phase audit. It also runs the final combined gate when either target evidence JSON file is committed to the repository.

When committed source-machine reports are present at \`docs/acceptance/local-web-real-nas.md\`, \`docs/acceptance/artifacts/local-web-sanity.json\`, or \`docs/acceptance/artifacts/real-nas-50-editor-report.json\`, this kit also includes a \`local/\` folder with copies for handoff. Run \`npm run sync:local-real-nas-record\` and then \`npm run audit:local-real-nas-phase\` before packaging when those local reports are present; sync refreshes the human acceptance record from the saved local Web report, then the audit revalidates the saved local Web report, runs the NAS 50-editor report self-check, and confirms the acceptance record includes the current evidence values. Those local reports remain preflight/rehearsal evidence only; they do not close ACC-008, ACC-009, or final delivery without target-machine evidence.

\`MANIFEST.json\` is generated with a SHA-256 digest, byte size, and executable flag for every packaged file except the manifest itself. Run \`npm run validate:evidence-kit-manifest\` and \`npm run validate:evidence-kit-drafts\` after packaging, or \`npm run validate:evidence-kit-manifest -- /path/to/mixlab-evidence-kit\` plus \`npm run validate:evidence-kit-drafts -- /path/to/mixlab-evidence-kit\` after downloading an artifact, to confirm a copied target folder still contains the same collectors, self-checks, README files, draft JSONs, and CI-prefilled installer/image metadata that CI uploaded. On target machines without the source repository, run the packaged root self-check instead:

\`\`\`powershell
powershell -ExecutionPolicy Bypass -File .\\evidence-kit-manifest-self-check.ps1 -KitDir .
\`\`\`

\`\`\`sh
sh ./evidence-kit-manifest-self-check.sh .
\`\`\`
`;

const TESTER_CHECKLIST = `# MixLab Target Tester Checklist

Use this checklist before declaring ACC-008, ACC-009, or final delivery complete.

## 0. Local Web Sanity

- Admin web returns 200 from http://127.0.0.1:5176/ during the current local Web real-NAS run, or from the deployed NAS admin URL during target testing.
- Admin dashboard shows core path health, keyword location, full transcript, segment cutting, 50-editor capacity, search p95, local search coverage, search failure count, material scale, active editor signals, and a disabled \`智能扫描\` write action until the real NAS write lock is explicitly unlocked, without exposing API keys or bearer tokens.
- Admin source videos shows \`真实 NAS 安全边界\` and keeps \`重试此视频\`, \`保存封面\`, and \`保存公开说明\` disabled before anyone unlocks \`真实 NAS 写入动作\`.
- Admin preprocessing shows \`真实 NAS 安全边界\`, \`只读观察\`, \`人工确认\`, and \`本机工作区\` before anyone runs queue, retry, recover, supervisor, publish, Doctor, or settings actions against real NAS data.
- Cutter web returns 200 from http://127.0.0.1:5177/ during the current local Web real-NAS run.
- Material Locator opens a known real-NAS query from http://127.0.0.1:5177/#material-locator?query=%E7%8E%B0%E9%87%91%E6%B5%81 before ad-hoc keyword testing.
- From the source repository, run npm run audit:local-web-sanity. It opens the cutter Material Locator, selects a transcript hit, exports the selected sentence context broader than the query keyword alone, verifies cut feedback, checks the local library contains the selected text, confirms local reusable materials appear before public materials after the cut, records material_locator_closed_loop.selection_proof_text, material_locator_closed_loop.selected_text_char_count, material_locator_closed_loop.selected_text_is_broader_than_query, material_locator_closed_loop.local_clip_id, local media/manifest file paths, local media/manifest existence and positive byte sizes, cut_job_id, cut_job_status=done, cut_job_export_clip_id mapped to local_clip_id, cut job output, Cut Tasks page selected-text/output/completed-status visibility, local_output_is_outside_public_library, and public_library_write_detected=false, records admin_dashboard.active_cutter_count and admin_dashboard.cutter_capacity with capacity at least 50, records admin_dashboard.current_index_version, records admin_dashboard.disabled_write_action_labels for \`智能扫描\`, records searchd_index.index_version and requires it to match the admin current index, records admin_real_nas_matrix for real PublicLibrary status, settings source folders, ready source detail transcript counts, preprocess jobs, index versions, cutter users, admin Web route rendering, admin_real_nas_matrix.source_video_web source path, first id, load-more, query API/result, and ready-filter all-ready proof, source_video_write_action_lock_labels for \`重试此视频\`, \`保存封面\`, and \`保存公开说明\`, visible preprocessing safety labels, disabled preprocessing write action labels, and skipped mutating actions, records cutter_search_matrix for multiple keyword searchd queries that match searchd_index.index_version, records layout.admin_statusbar, layout.admin_statusbar_item_overflow_count, layout.cutter_workbench, layout.cutter_body, layout.admin_route_layouts, and layout.cutter_route_layouts so admin and cutter screens cannot pass with horizontal overflow across their main route matrix at desktop 1440x960 and compact 1024x768 viewports, records material_locator.search_index_version and requires it to match searchd_index.index_version, records admin_dashboard.search_p95_ms no higher than 1000ms, records admin_dashboard.local_search_coverage_percent as a percentage at least 80%, records admin_dashboard.search_failure_count as 0, and records structured material_locator.current_hit_time_ms_value, material_locator.global_hit_position, material_locator.global_hit_count, material_locator.current_video_hit_count, material_locator.selected_sentence_count, and material_locator.full_transcript_char_count fields. The saved report must keep current-video hit count no higher than global hit count, full transcript character count greater than selected transcript text length, selected transcript text broader than the query keyword alone, selection_proof_text with source/time/character/hit proof, searchd index health matched to the admin current index, admin and cutter matrices matched to searchd index health, Material Locator search results matched to searchd index health, non-empty local media/manifest output files, and the completed cut job mapped back to the generated local clip. Set MIXLAB_LOCAL_WEB_SANITY_REPORT=docs/acceptance/artifacts/local-web-sanity.json to keep the JSON report, run npm run validate:local-web-sanity-report -- docs/acceptance/artifacts/local-web-sanity.json to revalidate the saved report, run npm run sync:local-real-nas-record after the source-machine 50-editor report exists to refresh docs/acceptance/local-web-real-nas.md from the saved JSON, run npm run audit:local-real-nas-phase, and confirm the printed local_web summary includes source_video_web_first_id, source_video_web_loaded_after, source_video_web_query_response_observed, source_video_web_ready_filter_all_visible_rows_ready, dashboard_write_action_lock_labels, source_video_write_action_lock_labels, preprocess_safety_labels, preprocess_write_action_lock_labels, material_query, material_candidate_count, selection_proof_text, selected_text_char_count, selected_text_is_broader_than_query, local_clip_id, cut_job_id, and public_library_write_detected=false. Override MIXLAB_ADMIN_WEB_URL or MIXLAB_ADMIN_WEB_BASE_URL, MIXLAB_ADMIN_API_BASE_URL, MIXLAB_CUTTER_WEB_URL or MIXLAB_CUTTER_WEB_BASE_URL, MIXLAB_CUTTER_API_BASE_URL, MIXLAB_SEARCHD_BASE_URL, MIXLAB_LOCAL_WEB_SANITY_QUERY, or MIXLAB_LOCAL_WEB_SANITY_MATRIX_QUERIES when testing non-default endpoints.
- The local Web closed loop must record material_locator_closed_loop.selection_method = transcript-drag, material_locator_closed_loop.selected_sentence_count at least 2, and material_locator_closed_loop.selected_text_segment_count at least 2, proving the user can drag-select continuous full-transcript context and that the actual selected text spans multiple transcript segments before cutting.
- Treat the local Web sanity report as a source-machine preflight only. It cannot close ACC-008, ACC-009, or final delivery without real Windows 10/11 and NAS/SMB target evidence.
- Cutter Material Locator can search a keyword, focus a public source video result, show the exact current hit time, global hit position, current-video hit count, selected sentence count, and full transcript character count, and write the matching structured material_locator fields into the saved local web sanity report.
- A tester can select continuous transcript text containing the hit and broader than the keyword alone, add it to the cut list, submit a cut, and see the new local clip in the local library.
- Do not paste ASR keys, signed URLs, full private transcripts, pasted search text, or bearer tokens into any evidence JSON or text attachment.

## 1. Windows ACC-008

- Run the Windows folder on one clean Windows 10 target and one clean Windows 11 target.
- Verify Node, npm, Git, ffmpeg, ffprobe, and the source repository are absent before the packaged app starts.
- Install the downloaded .exe, launch from the Start Menu, pass Doctor, confirm engine status, enter the workbench, locate material, complete one cut, open the project output folder, and verify the local library refreshes.
- Capture doctor-pass, engine-status, material-locator, completed-cut or cut-job, and local-library screenshots under captures/.
- Run windows-acc-008-collector.ps1 with -EvidenceDir .\\captures and -RequireCurrentEnvironmentComplete after every row is real.
- Run windows-evidence-self-check.ps1 before leaving each Windows target.

## 2. NAS ACC-009

- From the source repository, run npm run validate:nas-docker-compose-static before copying the NAS Docker project. This static check confirms the expected Compose services, public-library mount, worker command, count refresh default, and blank .env.example ASR key; it does not replace docker compose config or real NAS target evidence.
- Confirm the NAS Docker admin web is reachable, the admin API listens, the admin-worker loop starts, current.json is created, and worker logs include count_refresh_interval matching MIXLAB_PREPROCESS_COUNT_REFRESH_INTERVAL.
- Verify the deployed NAS admin source-videos page against the real public source path: first source video id is visible, load-more increases visible rows, a keyword query observes the API response and rendered result, and the ready filter observes the API response with only ready rows; copy those values into admin_source_videos_ui.
- Verify the SMB public library is readable from cutter machines and not writable by cutters.
- Use at least 2,000 indexed source videos and 48,000 indexed transcript segments.
- Complete the 50+ editor searchd flow: keyword search, full-transcript location, transcript selection, local cut submission, local clip output, zero search failures in metrics.usage.search_failure_count, public-library write protection, and cross-workspace isolation.
- Before collector copy, run nas-50-editor-report-self-check.sh ./captures/50-editor-report.json.
- Run nas-acc-009-collector.sh with EVIDENCE_DIR=./captures, then run nas-evidence-self-check.sh ./nas-acc-009.json before leaving the NAS shell host.

## 3. Return And Validate

- Copy windows-acc-008.json with screenshots/ and nas-acc-009.json with evidence/ back under docs/acceptance/evidence/.
- Keep MANIFEST.json with the downloaded target evidence kit so copied folders can be checked against the packaged collectors, self-checks, README files, and draft JSONs.
- Run npm run validate:evidence-kit-manifest and npm run validate:evidence-kit-drafts, or run them with -- /path/to/mixlab-evidence-kit after downloading an artifact, before handing the kit to target testers.
- On a target machine without the source repository, run powershell -ExecutionPolicy Bypass -File .\\evidence-kit-manifest-self-check.ps1 -KitDir . or sh ./evidence-kit-manifest-self-check.sh . from the downloaded kit root.
- Run npm run audit:target-evidence-readiness. It prints one short JSON summary for ACC-008, ACC-009, attachment counts, missing files, provenance commit matching, and next actions; it must fail until both target evidence packages are real and complete.
- Run npm run validate:windows-evidence -- docs/acceptance/evidence/windows-acc-008.json.
- Run npm run validate:nas-evidence -- docs/acceptance/evidence/nas-acc-009.json.
- Run npm run validate:target-evidence -- docs/acceptance/evidence/windows-acc-008.json docs/acceptance/evidence/nas-acc-009.json.
- Run npm run audit:delivery-readiness. It may only report ACC-008, ACC-009, and DELIV-001 open before real target evidence exists.
`;

const WINDOWS_README = `# ACC-008 Windows Evidence

Run this folder on a fresh Windows 10 or Windows 11 target machine.

\`\`\`powershell
powershell -ExecutionPolicy Bypass -File .\\windows-acc-008-collector.ps1 -EvidencePath .\\windows-acc-008.json -EvidenceDir .\\captures -RepositoryCommitSha "<40-char-commit-sha>" -EvidenceKitWorkflowRunUrl "https://github.com/alin155/mixlab/actions/runs/RUN_ID" -InstallerWorkflowRunUrl "https://github.com/alin155/mixlab/actions/runs/RUN_ID" -InstallerFilePath ".\\captures\\MixLab Cutter_0.1.0_x64-setup.exe" -InstallerVersion "0.1.0" -InstalledFromExe -LaunchedFromStartMenu -NoCommandLineRequired -DoctorPassed -DefaultWorkspacePathOk -EngineStatusNormal -EnteredWorkbench -AllPublicLibraryPathsPassed -AllFailureCasesPassed -RequireCurrentEnvironmentComplete
\`\`\`

The collector fills machine facts and preserves the full Windows path and failure matrices. It does not mark manual product checks as passed unless explicit parameters are supplied.

After collection, run the read-only target-side self-check while still on the Windows machine:

\`\`\`powershell
powershell -ExecutionPolicy Bypass -File .\\windows-evidence-self-check.ps1 -EvidencePath .\\windows-acc-008.json
\`\`\`

The self-check reports remaining empty strings, false flags, zero counts, missing/fake/undersized screenshot attachments, diagnostics samples missing the required stage/api/log/public/workspace/ffmpeg/ffprobe/doctor/retry terms, and obvious diagnostics secret/private-data markers. It is only a fast local sanity check; final acceptance still requires copying the JSON plus screenshots back to the repository and running the repository validators.

Set RepositoryCommitSha to the commit that produced the Windows installer and evidence kit artifacts. Pass InstallerFilePath when the downloaded .exe is available on the target machine so the collector records installer.file_sha256 with Get-FileHash; otherwise pass InstallerFileSha256 from the workflow artifact. The installer file name must include the recorded InstallerVersion. The final gate rejects missing provenance, missing installer SHA-256, mismatched installer file name/version evidence, and GitHub Actions run URLs outside https://github.com/alin155/mixlab.

When this kit is generated by the Cutter Desktop Windows Package workflow, RepositoryCommitSha, EvidenceKitWorkflowRunUrl, InstallerWorkflowRunUrl, InstallerFileName, InstallerFileSha256, and InstallerVersion are prefilled in the draft JSON.

When screenshot parameters are supplied, the collector verifies their .png, .jpg, .jpeg, or .webp file signatures, copies them into \`screenshots/<os>/\` beside \`windows-acc-008.json\`, and writes forward-slash relative attachment paths for validation. The Windows evidence validator rejects hand-edited screenshot references that use absolute paths, backslashes, parent-directory traversal, the wrong OS folder, or a filename stem that does not match its field; it also rejects missing, fake, or undersized screenshot files. When \`-EvidenceDir .\\captures\` is supplied, it auto-picks \`doctor-pass\`, \`engine-status\`, \`material-locator\`, \`cut-job\` or \`completed-cut\`, \`local-library\`, \`success-diagnostics.txt\`, and \`failure-diagnostics.txt\` from that folder if the individual parameters are omitted. Supplied diagnostics must be non-empty and include stage, api, log, public, workspace, ffmpeg, ffprobe, doctor, and retry. Use \`-RequireCurrentEnvironmentComplete\` on each Windows 10/11 target pass once all captures and matrix rows are ready; it fails before writing incomplete current-environment evidence. Use \`-AllPublicLibraryPathsPassed\` and \`-AllFailureCasesPassed\` after the tester has completed every row, or pass individual rows with \`-PassedPublicLibraryPath\` and \`-PassedFailureCase\` during partial collection.

Run once on Windows 10 and once on Windows 11, preserving the same \`windows-acc-008.json\` evidence file. When returning evidence to the repository, copy \`windows-acc-008.json\` and the generated \`screenshots/\` folder together under \`docs/acceptance/evidence/\`; the validators read those relative screenshot paths and fail if only the JSON is copied back.
`;

const WINDOWS_CAPTURES_README = `# Windows ACC-008 Captures

Place target screenshots and diagnostics here before running \`windows-acc-008-collector.ps1 -EvidenceDir .\\captures\`.

Recognized screenshot names:

- doctor-pass.png, .jpg, .jpeg, or .webp
- engine-status.png, .jpg, .jpeg, or .webp
- material-locator.png, .jpg, .jpeg, or .webp
- cut-job.png, .jpg, .jpeg, or .webp
- completed-cut.png, .jpg, .jpeg, or .webp
- local-library.png, .jpg, .jpeg, or .webp

Recognized diagnostics names:

- success-diagnostics.txt or diagnostics-success.txt
- failure-diagnostics.txt or diagnostics-failure.txt

Screenshots must be real .png, .jpg, .jpeg, or .webp files with matching file signatures and should be at least 640x360 for the final combined gate. Diagnostics must be non-empty, include stage, api, log, public, workspace, ffmpeg, ffprobe, doctor, and retry, and must not contain ASR keys, signed URLs, full private transcripts, pasted search text, or non-redacted bearer tokens. The collector rejects invalid screenshots, empty or weak diagnostics, and those text markers before writing the evidence JSON.
`;

const NAS_README = `# ACC-009 NAS Evidence

Run this folder on the NAS shell host after the Docker deployment and SMB tests.

\`\`\`sh
REPOSITORY_COMMIT_SHA=<40-char-commit-sha> \\
EVIDENCE_KIT_WORKFLOW_RUN_URL=https://github.com/alin155/mixlab/actions/runs/RUN_ID \\
ADMIN_WEB_URL=http://NAS_IP:8080 \\
IMAGE_TAG=<same-40-char-commit-sha> \\
MIXLAB_PREPROCESS_COUNT_REFRESH_INTERVAL=25 \\
PUBLIC_LIBRARY_HOST_PATH=/volume1/MixLab/PublicLibrary \\
WINDOWS_UNC_PATH='\\\\NAS\\MixLab\\PublicLibrary' \\
NAS_SHARED_FOLDER='共享文件夹/MixLab/PublicLibrary' \\
ADMIN_SOURCE_VIDEOS_SOURCE_PATH_VISIBLE=true \\
ADMIN_SOURCE_VIDEOS_FIRST_ID=V000001 \\
ADMIN_SOURCE_VIDEOS_FIRST_ID_VISIBLE=true \\
ADMIN_SOURCE_VIDEOS_LOADED_COUNT_BEFORE=100 \\
ADMIN_SOURCE_VIDEOS_LOADED_COUNT_AFTER=200 \\
ADMIN_SOURCE_VIDEOS_LOAD_MORE_INCREASED=true \\
ADMIN_SOURCE_VIDEOS_QUERY='房产' \\
ADMIN_SOURCE_VIDEOS_QUERY_RESULT_ID=V000001 \\
ADMIN_SOURCE_VIDEOS_QUERY_API_RESPONSE_OBSERVED=true \\
ADMIN_SOURCE_VIDEOS_QUERY_RESULT_VISIBLE=true \\
ADMIN_SOURCE_VIDEOS_READY_FILTER_SELECTED=true \\
ADMIN_SOURCE_VIDEOS_READY_FILTER_API_RESPONSE_OBSERVED=true \\
ADMIN_SOURCE_VIDEOS_READY_FILTER_VISIBLE_STATUS_COUNT=100 \\
ADMIN_SOURCE_VIDEOS_READY_FILTER_ALL_VISIBLE_ROWS_READY=true \\
EVIDENCE_DIR=./captures \\
sh ./nas-acc-009-collector.sh
\`\`\`

The collector fills deployment facts it can detect, records deployment.preprocess_count_refresh_interval from MIXLAB_PREPROCESS_COUNT_REFRESH_INTERVAL or an existing evidence draft, records admin_source_videos_ui from ADMIN_SOURCE_VIDEOS_* variables or preserved draft values, and leaves the remaining SMB and 50-editor evidence fields explicit. The completed admin_source_videos_ui proof must show the deployed NAS admin source-videos page rendered the real source path, a concrete source video id, load-more row growth, query API response plus rendered result, and ready-filter API response with all visible rows ready. The final 50-editor report must include indexed_source_video_count >= 2000, indexed_transcript_segment_count >= 48000, searchd_health_source_video_count equal to indexed_source_video_count, and searchd_health_segment_count equal to indexed_transcript_segment_count. Keep MIXLAB_PREPROCESS_COUNT_REFRESH_INTERVAL=25 in the NAS .env for large real preprocessing runs unless operators need more frequent dashboard count updates; successful items refresh aggregate library counts at that interval and once at worker-cycle end, while failures still refresh immediately. When EVIDENCE_DIR or individual attachment variables are supplied, it rejects empty attachments, verifies screenshot file signatures, parses .json attachments when Node or Python 3 is available, rejects worker.log files whose count_refresh_interval does not match deployment.preprocess_count_refresh_interval, and copies screenshots, logs, and reports into \`evidence/\` beside \`nas-acc-009.json\`; if no worker.log is supplied, it captures the last 200 lines from \`docker compose logs admin-worker\`. It writes forward-slash relative attachment paths for validation, and the NAS evidence validator rejects hand-edited attachment references that use absolute paths, backslashes, parent-directory traversal, filename stems that do not match their fields, missing files, fake or undersized screenshots, weak 50-editor reports, incomplete admin_source_videos_ui values, or mismatched worker logs.

After collection, run the read-only target-side self-check while still on the NAS shell host:

\`\`\`sh
sh ./nas-evidence-self-check.sh ./nas-acc-009.json
\`\`\`

The self-check reports remaining empty strings, false flags, zero counts, missing evidence attachments, fake or undersized screenshot attachments, and obvious 50-editor report draft markers. It is only a fast local sanity check; final acceptance still requires copying the JSON plus evidence/ folder back to the repository and running the repository validators.

Set REPOSITORY_COMMIT_SHA to the commit that produced the NAS Docker images and evidence kit artifacts. The final gate rejects missing provenance, rejects GitHub Actions run URLs outside https://github.com/alin155/mixlab, and rejects NAS evidence when deployment.image_tag does not match that commit.

When this kit is generated by the Build Admin Docker Images workflow, REPOSITORY_COMMIT_SHA, EVIDENCE_KIT_WORKFLOW_RUN_URL, IMAGE_TAG, and MIXLAB_PREPROCESS_COUNT_REFRESH_INTERVAL=25 are prefilled in the draft JSON. If those environment variables are not passed again on the NAS shell host, nas-acc-009-collector.sh preserves the prefilled provenance, image tag, and count-refresh interval from the existing nas-acc-009.json file.

The generated captures/50-editor-report.json is an intentionally failing draft with the required per-editor structure. Replace every draft status, zero metric, empty id, false top-level pass flag, false location_verified flag, and false closed-loop flag with real NAS/SMB target run values before running the collector; when Node is available on the NAS host, the collector rejects weak reports before copying them into evidence/50-editor-report.json. Before collector copy, run the read-only raw report self-check:

\`\`\`sh
sh ./nas-50-editor-report-self-check.sh ./captures/50-editor-report.json
\`\`\`

The final report must include top-level all_searches_passed, all_cuts_written_to_local_workspaces, public_library_not_written_by_cutters, and no_cross_workspace_outputs values set to true, top-level search_index_version matching every per-editor search_index_version from searchd, searchd_health_index_version matching search_index_version, searchd_health_source_video_count matching indexed_source_video_count, searchd_health_segment_count matching indexed_transcript_segment_count, metrics.usage.search_failure_count equal to 0, search_query_count and search_queries proving at least 5 distinct search_query values, plus per-editor search hit to full transcript location rows with search_result_rank inside the returned result list, search_result_group_count at least search_result_limit, search_result_limit at least 50, integer search_result_begin_char/search_result_end_char values mapped into the full-transcript character offsets, search_result_text_sha256 equal to sha256(search_query), full_transcript_source_video_id matching source_video_id, full_transcript_segment_count at least 4, full_transcript_char_count greater than selected_text_char_count, full_transcript_text_sha256, selected_text_begin_char/selected_text_end_char values proving the selected text range includes that hit, selected_text_char_count equal to selected range length, local_clip_source_video_id matching source_video_id, local_clip_selected_text_sha256 equal to selected_text_sha256, local_clip_relative_path as a workspace-relative portable path, local_clip_file_size_bytes as positive output file size, local_clip_content_sha256 as output file sha256, and local_clip_begin_ms/local_clip_end_ms matching selected_begin_ms/selected_end_ms, not only aggregate p95 and usage counts, and must not include target-machine run root fields such as library_root, workspace_root, or searchd_cache_root. When running the repository-based 50-editor searchd smoke as part of the NAS target run, prefer npm run smoke:searchd-nas-rehearsal; it defaults to MIXLAB_SEARCHD_CONCURRENCY_VIDEOS=2000, MIXLAB_SEARCHD_CONCURRENCY_SEGMENTS_PER_VIDEO=24, and captures/50-editor-report.json, and it rejects lower-scale overrides before running. Set MIXLAB_SEARCHD_NAS_REHEARSAL_RUN_ROOT=/path/to/target-mounted-run-root when the generated library/workspace/cache directories should live under a NAS or SMB-mounted acceptance folder instead of the system temp directory.

When returning NAS evidence to the repository, copy nas-acc-009.json and the generated evidence/ folder together under docs/acceptance/evidence/. The validators read those relative attachment paths and fail if only the JSON is copied back.

When node is available on the collector host and captures/50-editor-report.json exists, nas-acc-009-collector.sh derives editor_session_count and the multi-user pass/fail booleans from that report. If Node or the report is unavailable, set EDITOR_SESSION_COUNT, ALL_SEARCHES_PASSED, ALL_CUTS_WRITTEN_TO_LOCAL_WORKSPACES, MULTI_USER_PUBLIC_LIBRARY_NOT_WRITTEN_BY_CUTTERS, and NO_CROSS_WORKSPACE_OUTPUTS explicitly from the observed target run.
`;

async function writeJson(filePath: string, value: unknown): Promise<void> {
  await writeFile(filePath, `${JSON.stringify(value, null, 2)}\n`, "utf8");
}

interface EvidenceKitManifestFile {
  path: string;
  sha256: string;
  size_bytes: number;
  executable: boolean;
}

interface EvidenceKitManifest {
  schema_version: 1;
  artifact_name: typeof TARGET_EVIDENCE_KIT_ARTIFACT_NAME;
  generated_by: "npm run package:evidence-kit";
  source_commit_sha: string;
  github_actions_run_url: string;
  files: EvidenceKitManifestFile[];
}

function toPortablePath(filePath: string): string {
  return filePath.split(path.sep).join("/");
}

async function collectEvidenceKitFiles(rootDir: string, currentDir = rootDir): Promise<string[]> {
  const entries = await readdir(currentDir, { withFileTypes: true });
  const files: string[] = [];

  for (const entry of entries) {
    const entryPath = path.join(currentDir, entry.name);
    if (entry.isDirectory()) {
      files.push(...await collectEvidenceKitFiles(rootDir, entryPath));
      continue;
    }

    if (entry.isFile()) {
      const relativePath = toPortablePath(path.relative(rootDir, entryPath));
      if (relativePath !== "MANIFEST.json") {
        files.push(relativePath);
      }
    }
  }

  return files.sort((a, b) => a.localeCompare(b));
}

async function sha256File(filePath: string): Promise<string> {
  return createHash("sha256").update(await readFile(filePath)).digest("hex");
}

async function writeEvidenceKitManifest(
  outputDir: string,
  draftOptions: TargetEvidenceDraftOptions
): Promise<void> {
  const relativePaths = await collectEvidenceKitFiles(outputDir);
  const files = await Promise.all(relativePaths.map(async (relativePath) => {
    const filePath = path.join(outputDir, ...relativePath.split("/"));
    const fileStat = await stat(filePath);

    return {
      path: relativePath,
      sha256: await sha256File(filePath),
      size_bytes: fileStat.size,
      executable: (fileStat.mode & 0o111) !== 0
    };
  }));
  const manifest: EvidenceKitManifest = {
    schema_version: 1,
    artifact_name: TARGET_EVIDENCE_KIT_ARTIFACT_NAME,
    generated_by: "npm run package:evidence-kit",
    source_commit_sha: draftOptions.repository_commit_sha,
    github_actions_run_url: draftOptions.evidence_kit_workflow_run_url,
    files
  };

  await writeJson(path.join(outputDir, "MANIFEST.json"), manifest);
}

function githubActionsRunUrl(env: NodeJS.ProcessEnv): string {
  const serverUrl = env.GITHUB_SERVER_URL ?? "https://github.com";
  const repository = env.GITHUB_REPOSITORY ?? "";
  const runId = env.GITHUB_RUN_ID ?? "";
  if (!repository || !runId) {
    return "";
  }

  return `${serverUrl.replace(/\/$/, "")}/${repository}/actions/runs/${runId}`;
}

function positiveIntegerEnv(env: NodeJS.ProcessEnv, name: string): number | undefined {
  const value = env[name]?.trim();
  if (!value) {
    return undefined;
  }

  const parsed = Number(value);
  return Number.isInteger(parsed) && parsed > 0 ? parsed : undefined;
}

async function readCutterDesktopVersion(): Promise<string> {
  try {
    const packageJson = JSON.parse(await readFile("apps/cutter-desktop/package.json", "utf8")) as { version?: unknown };
    return typeof packageJson.version === "string" ? packageJson.version : "";
  } catch {
    return "";
  }
}

async function copyOptionalLocalSourceReports(outputDir: string): Promise<string[]> {
  const copiedKitPaths: string[] = [];

  for (const report of OPTIONAL_LOCAL_SOURCE_REPORTS) {
    try {
      const reportStat = await stat(report.source_path);
      if (!reportStat.isFile()) {
        continue;
      }
    } catch (error) {
      if (typeof error === "object" && error !== null && "code" in error && error.code === "ENOENT") {
        continue;
      }
      throw error;
    }

    const destination = path.join(outputDir, ...report.kit_path.split("/"));
    await mkdir(path.dirname(destination), { recursive: true });
    await copyFile(report.source_path, destination);
    copiedKitPaths.push(report.kit_path);
  }

  if (copiedKitPaths.length > 0) {
    await writeFile(path.join(outputDir, "local", "README.md"), LOCAL_SOURCE_REPORTS_README, "utf8");
  }

  return copiedKitPaths;
}

async function createDraftOptionsFromEnv(env: NodeJS.ProcessEnv = process.env): Promise<TargetEvidenceDraftOptions> {
  const runUrl = githubActionsRunUrl(env);
  const commitSha = env.GITHUB_SHA ?? "";
  const workflowName = env.GITHUB_WORKFLOW ?? "";
  const windowsInstallerWorkflowRunUrl = env.MIXLAB_WINDOWS_INSTALLER_WORKFLOW_RUN_URL
    ?? (workflowName === "Cutter Desktop Windows Package" ? runUrl : "");
  const windowsInstallerFileName = env.MIXLAB_WINDOWS_INSTALLER_FILE_NAME ?? "";
  const windowsInstallerSha256 = env.MIXLAB_WINDOWS_INSTALLER_SHA256 ?? "";
  const windowsInstallerVersion = env.MIXLAB_WINDOWS_INSTALLER_VERSION
    ?? (windowsInstallerWorkflowRunUrl ? await readCutterDesktopVersion() : "");
  const nasImageTag = env.MIXLAB_NAS_IMAGE_TAG
    ?? (workflowName === "Build Admin Docker Images" ? commitSha : "");
  const nasPreprocessCountRefreshInterval = positiveIntegerEnv(env, "MIXLAB_PREPROCESS_COUNT_REFRESH_INTERVAL")
    ?? (workflowName === "Build Admin Docker Images" ? DEFAULT_NAS_PREPROCESS_COUNT_REFRESH_INTERVAL : undefined);

  return {
    repository_commit_sha: commitSha,
    evidence_kit_workflow_run_url: runUrl,
    windows_installer_file_name: windowsInstallerFileName,
    windows_installer_sha256: windowsInstallerSha256,
    windows_installer_version: windowsInstallerVersion,
    windows_installer_workflow_run_url: windowsInstallerWorkflowRunUrl,
    nas_image_tag: nasImageTag,
    nas_preprocess_count_refresh_interval: nasPreprocessCountRefreshInterval
  };
}

export async function packageAcceptanceEvidenceKit(outputDir = EVIDENCE_KIT_DIR): Promise<string> {
  const windowsDir = path.join(outputDir, "windows");
  const nasDir = path.join(outputDir, "nas");
  const draftOptions = await createDraftOptionsFromEnv();

  await rm(outputDir, { recursive: true, force: true });
  await mkdir(windowsDir, { recursive: true });
  await mkdir(nasDir, { recursive: true });

  await writeFile(path.join(outputDir, "README.md"), ROOT_README, "utf8");
  await writeFile(path.join(outputDir, "TESTER-CHECKLIST.md"), TESTER_CHECKLIST, "utf8");
  await copyOptionalLocalSourceReports(outputDir);
  await copyFile(
    "scripts/acceptance/evidence-kit-manifest-self-check.ps1",
    path.join(outputDir, "evidence-kit-manifest-self-check.ps1")
  );
  await copyFile(
    "scripts/acceptance/evidence-kit-manifest-self-check.sh",
    path.join(outputDir, "evidence-kit-manifest-self-check.sh")
  );
  await writeFile(path.join(windowsDir, "README.md"), WINDOWS_README, "utf8");
  await mkdir(path.join(windowsDir, "captures"), { recursive: true });
  await writeFile(path.join(windowsDir, "captures", "README.md"), WINDOWS_CAPTURES_README, "utf8");
  await writeFile(path.join(nasDir, "README.md"), NAS_README, "utf8");
  await mkdir(path.join(nasDir, "captures"), { recursive: true });

  await copyFile(
    "scripts/acceptance/windows-acc-008-collector.ps1",
    path.join(windowsDir, "windows-acc-008-collector.ps1")
  );
  await copyFile(
    "scripts/acceptance/windows-evidence-self-check.ps1",
    path.join(windowsDir, "windows-evidence-self-check.ps1")
  );
  await copyFile(
    "scripts/acceptance/nas-acc-009-collector.sh",
    path.join(nasDir, "nas-acc-009-collector.sh")
  );
  await copyFile(
    "scripts/acceptance/nas-evidence-self-check.sh",
    path.join(nasDir, "nas-evidence-self-check.sh")
  );
  await copyFile(
    "scripts/acceptance/nas-50-editor-report-self-check.sh",
    path.join(nasDir, "nas-50-editor-report-self-check.sh")
  );
  await chmod(path.join(outputDir, "evidence-kit-manifest-self-check.sh"), 0o755);
  await chmod(path.join(nasDir, "nas-acc-009-collector.sh"), 0o755);
  await chmod(path.join(nasDir, "nas-evidence-self-check.sh"), 0o755);
  await chmod(path.join(nasDir, "nas-50-editor-report-self-check.sh"), 0o755);

  await writeJson(path.join(windowsDir, "windows-acc-008.json"), createWindowsAcceptanceEvidenceDraft(draftOptions));
  await writeJson(path.join(nasDir, "nas-acc-009.json"), createNasAcceptanceEvidenceDraft(draftOptions));
  await writeJson(path.join(nasDir, "captures", "50-editor-report.json"), createNasConcurrencyReportDraft());
  await writeEvidenceKitManifest(outputDir, draftOptions);

  return outputDir;
}

async function main(): Promise<void> {
  const [, , outputDir = EVIDENCE_KIT_DIR] = process.argv;
  const kitPath = await packageAcceptanceEvidenceKit(outputDir);
  console.log(`Wrote MixLab target evidence kit to ${kitPath}`);
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  void main().catch((error) => {
    console.error(error instanceof Error ? error.message : error);
    process.exitCode = 1;
  });
}
